# Jovian Betanet on u17
l2chains = [
    {name = "Soneium devnet", chainId = 179182},
]

fallbackAddressesJsonPath = "src/tasks/sep/041-soneium-devnet-upgrade-v500/addresses.json"
templateName = "OPCMUpgradeV500"
allowOverwrite = ["SuperchainConfig", "SuperchainConfigProxyAdmin"]

[[opcmUpgrades]]
chainId = 179182
absolutePrestate = "0x038512e02c4c3f7bdaec27d00edf55b7155e0905301e1a88083e4e0a6764d54c"
expectedValidationErrors = "OVERRIDES-L1PAOMULTISIG,OVERRIDES-CHALLENGER"

[addresses]
OPCM = "0x704d236a529d7488669ff0627988e9ff7f3a1ecf"
StandardValidatorV500 = "0x60c6a1b11f6e7a157495a09c7d84cba4a71e0b71"
SuperchainConfig = "0xc92831eB4544053Dc330AB2cD4164e1EB3157A8E"
SuperchainConfigProxyAdmin = "0x664e70e3d58eee0eef8b6b192015f43ab7323007"

[stateOverrides]
0xFB0F8937A0d6999C67E8a01310eBf7fe1859205F = [
    {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 41}
]