# Soneium Devnet Contract Upgrade
l2chains = [
    {name = "Soneium devnet", chainId = 179182},
]

fallbackAddressesJsonPath = "src/tasks/sep/040-soneium-devnet-upgrade-v410/addresses.json"
templateName = "OPCMUpgradeV410"

[[opcmUpgrades]]
chainId = 179182
absolutePrestate = "0x038512e02c4c3f7bdaec27d00edf55b7155e0905301e1a88083e4e0a6764d54c"
expectedValidationErrors = ""

[addresses]
OPCM = "0xd07a89cf19869ce185a5ec173568ae8acd5d8c02"
StandardValidatorV410 = "0x44b5B4E785aFb3Ee5654Dfeb2Eff014ca435C1b4"

[stateOverrides]
0xFB0F8937A0d6999C67E8a01310eBf7fe1859205F = [
    {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 40}
]